# Generated by Django 6.0.5 on 2026-05-08 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncmetadata',
            name='last_changed_at',
            field=models.DateTimeField(default=datetime.datetime(1999, 12, 31, 21, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
