# Generated by Django 6.0.5 on 2026-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_outboxmessage_registration_idempotency_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('cancelled', 'Cancelled')], db_index=True, default='reserved', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved')), fields=('event', 'seat'), name='unique_active_reservation'),
        ),
    ]
